import { boolean, integer, jsonb, pgEnum, pgTable, real, text, timestamp, uuid, varchar } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };
export const role = pgEnum("role", ["STUDENT", "FACULTY", "MENTOR", "EXAMINER", "LAB_INSTRUCTOR", "ADMIN", "AI_AGENT", "SYSTEM"]);
export const submissionStatus = pgEnum("submission_status", ["DRAFT", "SUBMITTED", "REVIEWED", "RETURNED"]);
export const labStatus = pgEnum("lab_status", ["READY", "RUNNING", "COMPLETED", "EXPIRED", "DESTROYED"]);
export const enrollmentStatus = pgEnum("enrollment_status", ["ENROLLED", "IN_PROGRESS", "COMPLETED", "DROPPED", "FAILED"]);
export const masteryLevel = pgEnum("mastery_level", ["BEGINNING", "DEVELOPING", "PROFICIENT", "ADVANCED", "MASTERED"]);

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), externalId: varchar("external_id", { length: 255 }).unique(), email: varchar("email", { length: 320 }).notNull().unique(), displayName: varchar("display_name", { length: 180 }).notNull(), role: role("role").default("STUDENT").notNull(), active: boolean("active").default(true).notNull(), ...timestamps });
export const programs = pgTable("programs", { id: uuid("id").defaultRandom().primaryKey(), code: varchar("code", { length: 40 }).notNull().unique(), title: varchar("title", { length: 240 }).notNull(), credits: integer("credits").notNull(), description: text("description"), ...timestamps });
export const courses = pgTable("courses", { id: uuid("id").defaultRandom().primaryKey(), programId: uuid("program_id").references(() => programs.id), code: varchar("code", { length: 40 }).notNull().unique(), title: varchar("title", { length: 240 }).notNull(), credits: integer("credits").notNull(), year: integer("year").notNull(), term: varchar("term", { length: 40 }).notNull(), ...timestamps });
export const competencies = pgTable("competencies", { id: uuid("id").defaultRandom().primaryKey(), code: varchar("code", { length: 60 }).notNull().unique(), title: varchar("title", { length: 240 }).notNull(), description: text("description").notNull(), framework: varchar("framework", { length: 120 }).notNull(), ...timestamps });
export const evidence = pgTable("evidence", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), competencyId: uuid("competency_id").references(() => competencies.id).notNull(), kind: varchar("kind", { length: 60 }).notNull(), uri: text("uri"), metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(), ...timestamps });
export const studentCompetencies = pgTable("student_competencies", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), competencyId: uuid("competency_id").references(() => competencies.id).notNull(), mastery: real("mastery").default(0).notNull(), confidence: real("confidence").default(0).notNull(), evidenceCount: integer("evidence_count").default(0).notNull(), ...timestamps });
export const academicTerms = pgTable("academic_terms", { id: uuid("id").defaultRandom().primaryKey(), code: varchar("code", { length: 20 }).notNull().unique(), name: varchar("name", { length: 120 }).notNull(), startDate: timestamp("start_date", { withTimezone: true }), endDate: timestamp("end_date", { withTimezone: true }), isCurrent: boolean("is_current").default(false).notNull(), ...timestamps });
export const enrollments = pgTable("enrollments", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), courseId: uuid("course_id").references(() => courses.id).notNull(), academicTermId: uuid("academic_term_id").references(() => academicTerms.id), status: enrollmentStatus("status").default("ENROLLED").notNull(), grade: real("grade"), completedAt: timestamp("completed_at", { withTimezone: true }), ...timestamps });
export const lessons = pgTable("lessons", { id: uuid("id").defaultRandom().primaryKey(), courseId: uuid("course_id").references(() => courses.id), code: varchar("code", { length: 40 }).notNull().unique(), title: varchar("title", { length: 240 }).notNull(), description: text("description").notNull(), orderIndex: integer("order_index").default(0).notNull(), ...timestamps });
export const studentLessonProgress = pgTable("student_lesson_progress", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), lessonId: uuid("lesson_id").references(() => lessons.id).notNull(), completed: boolean("completed").default(false).notNull(), completedAt: timestamp("completed_at", { withTimezone: true }), timeSpentMinutes: integer("time_spent_minutes").default(0).notNull(), ...timestamps });
export const evaluations = pgTable("evaluations", { id: uuid("id").defaultRandom().primaryKey(), lessonId: uuid("lesson_id").references(() => lessons.id), title: varchar("title", { length: 240 }).notNull(), description: text("description").notNull., kind: varchar("kind", { length: 60 }).notNull., criteria: jsonb("criteria").$type<Record<string, unknown>>().default({}).notNull., passingScore: real("passing_score").default(70).notNull., ...timestamps });
export const studentEvaluations = pgTable("student_evaluations", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), evaluationId: uuid("evaluation_id").references(() => evaluations.id).notNull., score: real("score"), status: submissionStatus("status").default("DRAFT").notNull., submittedAt: timestamp("submitted_at", { withTimezone: true }), feedback: text("feedback"), ...timestamps });
export const studentEvaluationsHistory = pgTable("student_evaluations_history", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull., evaluationId: uuid("evaluation_id").references(() => evaluations.id).notNull., previousScore: real("previous_score"), change: real("change"), changedAt: timestamp("changed_at", { withTimezone: true }), changedBy: varchar("changed_by", { length: 100 }), ...timestamps });
export const aiAuditEvents = pgTable("ai_audit_events", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id), agentId: varchar("agent_id", { length: 80 }).notNull(), action: varchar("action", { length: 120 }).notNull(), tool: varchar("tool", { length: 120 }), authorization: varchar("authorization", { length: 40 }).notNull(), inputMetadata: jsonb("input_metadata").$type<Record<string, unknown>>().default({}).notNull(), outputMetadata: jsonb("output_metadata").$type<Record<string, unknown>>().default({}).notNull(), result: varchar("result", { length: 40 }).notNull(), error: text("error"), ...timestamps });

export const academicYears = pgTable("academic_years", { id: uuid("id").defaultRandom().primaryKey(), year: integer("year").notNull().unique(), title: varchar("title", { length: 180 }).notNull(), description: text("description"), active: boolean("active").default(true).notNull(), ...timestamps });
export const modules = pgTable("modules", { id: uuid("id").defaultRandom().primaryKey(), courseId: uuid("course_id").references(() => courses.id).notNull(), title: varchar("title", { length: 240 }).notNull(), order: integer("order").notNull(), ...timestamps });
export const lessons = pgTable("lessons", { id: uuid("id").defaultRandom().primaryKey(), moduleId: uuid("module_id").references(() => modules.id).notNull(), title: varchar("title", { length: 240 }).notNull(), content: text("content").notNull(), type: varchar("type", { length: 40 }).notNull(), order: integer("order").notNull(), learningObjectives: jsonb("learning_objectives").$type<string[]>().default([]).notNull(), competencies: jsonb("competencies").$type<string[]>().default([]).notNull(), published: boolean("published").default(false).notNull(), ...timestamps });
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), title: varchar("title", { length: 240 }).notNull(), message: text("message").notNull(), type: varchar("type", { length: 40 }).notNull(), read: boolean("read").default(false).notNull(), data: jsonb("data").$type<Record<string, unknown>>().default({}).notNull(), ...timestamps });
export const tasks = pgTable("tasks", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id), kind: varchar("kind", { length: 40 }).notNull(), status: varchar("status", { length: 40 }).notNull(), progress: integer("progress").default(0).notNull(), error: text("error"), ...timestamps });
export const taskEvents = pgTable("task_events", { id: uuid("id").defaultRandom().primaryKey(), taskId: uuid("task_id").references(() => tasks.id).notNull(), state: varchar("state", { length: 40 }).notNull(), message: text("message"), metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(), ...timestamps });
export const aiAgents = pgTable("ai_agents", { id: varchar("id", { length: 80 }).primaryKey(), description: text("description").notNull(), capabilities: jsonb("capabilities").$type<string[]>().default([]).notNull(), permissions: jsonb("permissions").$type<string[]>().default([]).notNull(), active: boolean("active").default(true).notNull(), ...timestamps });
export const aiActions = pgTable("ai_actions", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id), agentId: varchar("agent_id", { length: 80 }).references(() => aiAgents.id).notNull(), action: varchar("action", { length: 120 }).notNull(), authorization: varchar("authorization", { length: 40 }).notNull(), result: varchar("result", { length: 40 }).notNull(), ...timestamps });

export const academicRecords = pgTable("academic_records", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), programId: uuid("program_id").references(() => programs.id), status: varchar("status", { length: 40 }).default("active").notNull(), ...timestamps });
export const credentials = pgTable("credentials", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), kind: varchar("kind", { length: 40 }).notNull(), title: varchar("title", { length: 240 }).notNull(), status: varchar("status", { length: 40 }).default("draft").notNull(), verificationUrl: text("verification_url"), evidenceIds: jsonb("evidence_ids").$type<string[]>().default([]).notNull(), ...timestamps });
export const researchSources = pgTable("research_sources", { id: uuid("id").defaultRandom().primaryKey(), title: varchar("title", { length: 240 }).notNull(), uri: text("uri").notNull(), sourceType: varchar("source_type", { length: 50 }).notNull(), approved: boolean("approved").default(false).notNull(), ...timestamps });
