export type Lesson = { id: string; title: string; type: "theory" | "practice" | "lab" | "assessment"; minutes: number; objective: string; content: string; evidencePrompt?: string };
export type CurriculumCourse = { code: string; title: string; year: number; credits: number; description: string; competencies: string[]; lessons: Lesson[] };
export const curriculum: CurriculumCourse[] = [
 { code: "LIN-101", title: "Linux Operations", year: 1, credits: 4, description: "Procesos, permisos, shell y hardening básico.", competencies: ["LINUX-FOUNDATIONS"], lessons: [{ id: "lin-101-1", title: "Filesystem, users and permissions", type: "theory", minutes: 25, objective: "Explicar el modelo de permisos Unix.", content: "Un sistema seguro empieza por saber quién puede leer, escribir y ejecutar. Trabajarás con usuarios, grupos, chmod, umask y sudo." }, { id: "lin-101-2", title: "Practice: least privilege checklist", type: "practice", minutes: 30, objective: "Aplicar mínimo privilegio en una máquina de práctica.", content: "Audita una lista de cuentas y justifica cada permiso. Separa observación, riesgo y remediación.", evidencePrompt: "Entrega una tabla con tres hallazgos y su remediación." }] },
 { code: "NET-101", title: "Networks & Protocols", year: 1, credits: 4, description: "TCP/IP, DNS, HTTP, routing y observabilidad.", competencies: ["NETWORK-FOUNDATIONS"], lessons: [{ id: "net-101-1", title: "Packets, ports and protocols", type: "theory", minutes: 28, objective: "Relacionar capas, puertos y protocolos.", content: "Mapea una petición web desde el navegador hasta el servidor y distingue transporte, aplicación y resolución de nombres." }, { id: "net-101-2", title: "Lab: read a network capture", type: "lab", minutes: 45, objective: "Extraer evidencia de una captura sintética.", content: "Identifica handshake, consulta DNS y petición HTTP en una captura proporcionada por el laboratorio.", evidencePrompt: "Presenta una línea temporal con paquetes y una hipótesis comprobable." }] },
 { code: "PY-101", title: "Python for Defense", year: 1, credits: 4, description: "Automatización segura, parsing y tests.", competencies: ["SECURE-PROGRAMMING"], lessons: [{ id: "py-101-1", title: "Data parsing without surprises", type: "theory", minutes: 30, objective: "Procesar entradas no confiables de forma segura.", content: "Aprende validación, tipos, errores y separación entre datos y comandos." }, { id: "py-101-2", title: "Practice: build a log parser", type: "practice", minutes: 40, objective: "Construir un parser determinista con tests.", content: "Extrae timestamp, actor y acción de registros sintéticos. No ejecutes comandos derivados de la entrada.", evidencePrompt: "Incluye código, tests y dos casos de entrada inválida." }] },
 { code: "CY-101", title: "Cybersecurity Fundamentals", year: 1, credits: 3, description: "Riesgo, amenazas, controles, ética y respuesta.", competencies: ["CYBER-FUNDAMENTALS"], lessons: [{ id: "cy-101-1", title: "Risk is a decision", type: "theory", minutes: 22, objective: "Diferenciar amenaza, vulnerabilidad, impacto y riesgo.", content: "La seguridad profesional comunica decisiones: qué puede ocurrir, con qué probabilidad, qué impacto tiene y qué control es proporcional." }, { id: "cy-101-2", title: "Assessment: explain a control", type: "assessment", minutes: 35, objective: "Justificar un control con evidencia.", content: "Selecciona un control para un escenario ficticio y defiende su eficacia y sus límites.", evidencePrompt: "Escribe una recomendación con contexto, evidencia, incertidumbre y siguiente acción." }] },
 { code: "WEB-201", title: "Web Application Security", year: 2, credits: 4, description: "Sesiones, validación, autorización y OWASP.", competencies: ["WEB-SECURITY"], lessons: [{ id: "web-201-1", title: "Authorization is not authentication", type: "theory", minutes: 32, objective: "Detectar fallos de control de acceso.", content: "Modela sujeto, recurso, acción y política. Prueba siempre el caso negativo: otro usuario, otro tenant y rol insuficiente." }, { id: "web-201-2", title: "Lab: threat model an API", type: "lab", minutes: 50, objective: "Crear un threat model con mitigaciones.", content: "Analiza una API ficticia, prioriza riesgos y propone controles verificables.", evidencePrompt: "Entrega un diagrama de flujo de datos y cinco casos de autorización." }] },
 { code: "SOC-301", title: "Detection Engineering", year: 3, credits: 4, description: "Telemetría, reglas, falsos positivos y cobertura.", competencies: ["DETECTION-ENGINEERING"], lessons: [{ id: "soc-301-1", title: "From signal to detection", type: "theory", minutes: 35, objective: "Convertir una hipótesis de amenaza en una detección.", content: "Define fuente, señal, contexto, severidad, ventana temporal y respuesta esperada." }, { id: "soc-301-2", title: "Lab: triage a suspicious alert", type: "lab", minutes: 55, objective: "Investigar una alerta sintética y documentar la decisión.", content: "Usa evidencia limitada, registra incertidumbre y evita atribuciones no demostradas.", evidencePrompt: "Presenta timeline, hipótesis, evidencia a favor/en contra y decisión." }] },
 { code: "IR-401", title: "Incident Response", year: 4, credits: 4, description: "Preparación, contención, erradicación y lecciones aprendidas.", competencies: ["INCIDENT-RESPONSE"], lessons: [{ id: "ir-401-1", title: "Make the first decision reversible", type: "theory", minutes: 30, objective: "Priorizar acciones seguras bajo presión.", content: "Preserva evidencia, reduce daño y evita acciones irreversibles sin autorización. Documenta quién decide y por qué." }, { id: "ir-401-2", title: "Capstone: write the incident report", type: "assessment", minutes: 90, objective: "Crear un informe profesional basado en evidencia.", content: "Construye un informe para una organización ficticia, separando hechos, inferencias y preguntas abiertas.", evidencePrompt: "Entrega resumen ejecutivo, timeline, impacto, decisiones y plan de mejora." }] },
];
export const curriculumByYear = (year: number) => curriculum.filter(course => course.year === year);
export const findLesson = (id: string) => curriculum.flatMap(course => course.lessons.map(lesson => ({ course, lesson }))).find(item => item.lesson.id === id);
